import type {Metadata} from "next";
import "./globals.css";
import {ConditionalLayout} from "@/components/conditional-layout";
import {StoreProvider} from "@/store/StoreProvider";
import localFont from "next/font/local";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} bg-[#E0EEFF]`}
        >
        <StoreProvider>
            <ConditionalLayout>
                {children}
            </ConditionalLayout>
        </StoreProvider>
        </body>
        </html>
    );
}
